on: [push, pull_request]
name: build
jobs:
  runhaskell:
    name: oniongen-hs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.3'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build 
