on: [push, pull_request]
name: build
jobs:
  runhaskell:
    strategy:
         matrix:
           os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: oniongen-hs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.3'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build 
